### ISSUE TITLE
Successfully installed but then what?

### ISSUE THREAD

**Issue by Willywang8216** [ckx000/get-cookies#10]
As the title, I'm not sure how to use it. 
Inside the option, I put 2 lines of urls for the sites I'd like to auto check in. Visit the site and log in... nothing happened. What exactly do I need to do to get the cookies or other neccessary stuffs ??

**Comment by ckx000** [comment]
Translated from google

no. this's wrong
This tool cannot directly get the cookies of the target website
It needs to work with other web pages
You cannot enter the address of the website you want to get cookies in the options
(Use A to get B's cookie，
You cannot enter the address of B[webaddress] . You have to enter the address of A[webaddress])

A=tool web address
The correct usage of this tool is:
Enter the tool web address  in the options:
For example: use https://github.com/qd-today/qd  to set up your own website. Then enter the access address of your own web page into the option box


> As the title, I'm not sure how to use it. Inside the option, I put 2 lines of urls for the sites I'd like to auto check in. Visit the site and log in... nothing happened. What exactly do I need to do to get the cookies or other neccessary stuffs ??
