### ISSUE TITLE
成功安装后，但是在签到框架无法调用呢，最新的120谷歌浏览器

### ISSUE THREAD

**Issue by asnon** [ckx000/get-cookies#11]
调用不了呢，后面只能手动去复制cookie了~麻烦大佬看一下~~

**Comment by qingyuan0o0** [comment]
119内核测试了下也不行

**Comment by ckx000** [comment]
打开chrome-扩展程序 找到添加的获取插件 ，查看是否有错误，如果有 点开错误按钮 看看是什么错误
同时
之前扩展程序页面 点开 Cookies获取助手下面的【查看视图 Service Worker】。会新开一个带控制台的页面，然后前往你所激活（就是你在扩展设置里填写的激活域名或ip）的签到页面的标签页，刷新页面。查看控制台是否有输出任何提示。提交看一下

**Comment by ati9527** [comment]
试了一下，edge里面要在扩展选项里面加上你用到的域名，刷新后就行了。
![image](https://github.com/qd-today/get-cookies/assets/55564669/ea74c3ba-15da-47d3-94d3-b3d07f4f7cab)

**Comment by ckx000** [comment]
> 试了一下，edge里面要在扩展选项里面加上你用到的域名，刷新后就行了。 ![image](https://private-user-images.githubusercontent.com/55564669/310198779-ea74c3ba-15da-47d3-94d3-b3d07f4f7cab.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk2NTgyOTEsIm5iZiI6MTcwOTY1Nzk5MSwicGF0aCI6Ii81NTU2NDY2OS8zMTAxOTg3NzktZWE3NGMzYmEtMTVkYS00N2QzLTk0ZDMtYjNkMDdmNGY3Y2FiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzA1VDE2NTk1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY4M2MxNTNjYmEzOWMyNWMwODA2Yzk0OTJmOGYyYzlhZTc5MGEyZjI2MGU5NTM4NjFhOWJhMDFkMGY3MTY0OWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GkrSedwemHvvah4qjkxYs7DUT-Be7fcqT4k1wp00pvs)

我就知道。。有可能是这原因。。你们仔细看一下安装说明，我都有写，要先把需要调用的站点域名写进去
插件的启用本质是白名单

**Comment by xueba0458** [comment]
chrome将鼠标移动到Cookie获取助手的上面，单击鼠标左键打开如下界面
![image](https://github.com/qd-today/get-cookies/assets/51258772/d2e86b7e-157b-46e8-8fa5-4a0d26b97bf6)
再左键单击选项，就会打开如下界面
![image](https://github.com/qd-today/get-cookies/assets/51258772/2d69ca47-fdb5-44a6-938e-1123bb6df341)
输入QD所在服务器的ip地址，然后Save就行了！
好像是作者忘记写到说明里了....

**Comment by ckx000** [comment]
使用说明那我可是写了个注意 看来你们都没看到。。

**Comment by ckx000** [comment]
把图片放进去了(/°▽ °) /

**Comment by Lounwb** [comment]
使用服务器ip(海外)，在Service Worker中监控不到网络活动。
我在本机上测试使用 使用127.0.0.1 / 内网地址都无法监控到网络活动。
这是为什么呢

get-cookies版本: 2.0.0
qt-today版本:20240210

**Comment by peoplechinapower** [comment]
感谢 有帮助到

**Comment by miaoxiaozhao** [comment]
【带端口的IP】【域名】如何填写？有标准格式么？

**Comment by ckx000** [comment]
> 【带端口的IP】【域名】如何填写？有标准格式么？

不需要写端口 只需要ip或者域名就可以

**Comment by guotao** [comment]
现在安装crx需要白名单才行了 ， https://kainy.cn/SyncMeIn/install.html 详细步骤。

**Comment by ckx000** [comment]
> 现在安装crx需要白名单才行了 ， https://kainy.cn/SyncMeIn/install.html 详细步骤。

本插件已不需要这么麻烦了，因为已经上架了，同时Releases里提供的crx也是商店版本 附带签名数据，即直接使用crx安装也如同访问扩展商店安装一样

**Comment by dongjinl** [comment]
edge扩展商店的版本还是0.0.6，没有扩展选项，直接下载Releases里提供的crx安装后才有扩展选项

**Comment by cy28438981** [comment]
限制又失效了，添加了nas的IP，获取不了
