### ISSUE TITLE
使用谷歌浏览器下载后就被删除，无法打开

### ISSUE THREAD

**Issue by LatteFang** [ckx000/get-cookies#12]
使用谷歌浏览器下载后就被删除，无法打开

**Comment by refrain1128** [comment]
edge浏览器也一样

**Comment by refrain1128** [comment]
下载那个zip包[https://github.com/qd-today/get-cookies/archive/refs/tags/v2.0.0.zip](url)，完成后解压，到浏览器里导入解压后的文件夹就可以了，不过我安装成功了点击扩展还是没反应

**Comment by enyucao** [comment]
解决方案：
不要下载CRX文件（缺少签名）
下载源代码， win用zip，mac用tar.gx
解压出来
插件市场选择导入已解压
右键插件，点击“扩展选项”，填入QD所在主机的IP

**Comment by ckx000** [comment]
应该是新版chrome验证CRX来源的问题了，以前只是提示CRX不是来自chrome应用商店，现在是直接删除的问题了。
推荐使用压缩包方式安装

**Comment by guotao** [comment]
现在安装crx需要白名单才行了 ， https://kainy.cn/SyncMeIn/install.html 👈 详细步骤。

**Comment by ckx000** [comment]
> 现在安装crx需要白名单才行了 ， https://kainy.cn/SyncMeIn/install.html 👈 详细步骤。

本插件已不需要这么麻烦了，因为已经上架了，同时Releases里提供的crx也是商店版本 附带签名数据，即直接使用crx安装也如同访问扩展商店安装一样
