### ISSUE TITLE
bug 

### ISSUE THREAD

**Issue by FellBan** [ckx000/get-cookies#2]
前端获取cookie没问题
![image](https://user-images.githubusercontent.com/13709020/166182080-6ed7eca9-7623-46f7-9e8b-8bbcbd28a337.png)

后端测试那里获取不了cookie
![image](https://user-images.githubusercontent.com/13709020/166182069-04e9a5d1-c575-4fc9-8267-572b11db7f80.png)

**Comment by ckx000** [comment]
这并不是一个bug，是框架的问题，暂时性的写了对应错误修复
