### ISSUE TITLE
扩展无法使用

### ISSUE THREAD

**Issue by jiankong123** [ckx000/get-cookies#3]
在选项中设置加载网站后，点击和原来一样是信息界面

**Comment by jiankong123** [comment]
> 在选项中设置加载网站后，点击和原来一样是信息界面

浏览器是360极速浏览器
使用edge浏览器后报错
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.
{
   "background": {
      "scripts": ["background.js"],
      "persistent": false
   },
   "default_locale": "zh_CN",
   "description": "__MSG_description__",
   "icons": {
      "32": "images/logo32.png",
      "16": "images/logo16.png",
      "48": "images/logo48.png",
      "128": "images/logo128.png"
   },
   "options_ui":{
      "page": "options/options.html",
      "open_in_tab": false,
      "chrome_style": true
   },
   "manifest_version": 2,
   "key": "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyqfMOCKmBFCyUDyIA2BKpJJhZnwYd4xBvu3B9ppdOQ98LYtK8pEcSGLpyhuzyiwtmlm9faAimQbCjelk1NGs/rkOTQFeC+X4TI4soujKA3v4vW1+QACchIiLCVel3nIJzU2Xq1vdbgP74wMWZ766xUqP4y6nNnGOaFvAWK+CuXPXOlNxbQ5ipNGUDR3MLz+PuLh1HtaMjtXWeJ5ailm8Rhuax9wAo1FcE/DwiRTbv11et/2MTda7Xo/3Z8S7Sc1gDbwHGFYRT931A3a+FUTTwiEDPP4LZmjBxgyknaBnj1Zh46kNYdaN1LFq3/0HloHq/E6B8rHXozqVHucaob+oMwIDAQAB",
   "permissions": [ "cookies", "storage", "tabs", "\u003Call_urls>"],
   "name": "__MSG_appName__",
   "version": "1.0.3"
}

   "manifest_version": 2,

**Comment by zhgjsony** [comment]
一样

**Comment by ckx000** [comment]
看了下我的平台。在chrome107下扩展没有任何报错。。你这边那2个浏览器就不清楚了。看错误报告提示的是mv2的写法被抛弃了？有具体故障截图吗？之前edge版本有正常使用过吗

**Comment by jiankong123** [comment]
> 
使用360极速浏览器不报错，但是一键获取cookie是哪个键啊，装了扩展点击没反应，使用qiandao.today平台的时候也没办法获取cookie

使用edge浏览器报错，但是也可以加载，F12显示getcookieload，但是cookie在哪啊

**Comment by jiankong123** [comment]
> 看了下我的平台。在chrome107下扩展没有任何报错。。你这边那2个浏览器就不清楚了。看错误报告提示的是mv2的写法被抛弃了？有具体故障截图吗？之前edge版本有正常使用过吗

使用360极速浏览器不报错，但是一键获取cookie是哪个键啊，装了扩展点击没反应，使用qiandao.today平台的时候也没办法获取cookie

使用edge浏览器报错，但是也可以加载，F12显示getcookieload，但是cookie在哪啊

**Comment by ckx000** [comment]
搜了下各种消息 应该是扩展的Manifest V2规范要被弃用了。在全面推Manifest V3。看了下v3似乎变化挺大的。晚些时候我看看能否更新到v3.目前要用的话建议先使用旧版edge。或者使用chrome.chrome 这边被推迟到明年才弃用v2

**Comment by xsm123006** [comment]
chrome也不能用了

**Comment by ckx000** [comment]
已更新至Manifest V3,请移步[Releases](https://github.com/ckx000/get-cookies/releases)
