### ISSUE TITLE
Edge最新版无法使用

### ISSUE THREAD

**Issue by Noahsarker** [ckx000/get-cookies#4]
版本 111.0.1661.41 (正式版本) (64 位)
加载提示：
Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

**Comment by ckx000** [comment]
#3 
同样的问题

**Comment by ckx000** [comment]
已更新至Manifest V3,请移步 [Releases](https://github.com/ckx000/get-cookies/releases)下载新版测试

**Comment by guotao** [comment]
现在安装crx需要白名单才行了 ， https://kainy.cn/SyncMeIn/install.html 详细步骤。

**Comment by ckx000** [comment]
> 现在安装crx需要白名单才行了 ， https://kainy.cn/SyncMeIn/install.html 详细步骤。

本插件按理是不需要的，因为已经上架了
