### ISSUE TITLE
今天 Chrome 更新完彻底不支持 `Manifest V2` 了，请大佬更新一下升级到 `Manifest V3` ，万分感激

### ISSUE THREAD

**Issue by FrancisNGG** [ckx000/get-cookies#7]
今天 Chrome 更新完彻底不支持 `Manifest V2` 了，请大佬更新一下升级到 `Manifest V3` ，万分感激。

另外我自己尝试按 `Manifest V3` 标准修改了 `Manifest.json` ，修改内容如下 ：

```
{
   "manifest_version": 3,
   "name": "__MSG_appName__",
   "version": "0.0.7",
   "description": "__MSG_description__",
   "icons": {
      "16": "images/logo16.png",
      "32": "images/logo32.png",
      "48": "images/logo48.png",
      "128": "images/logo128.png"
   },
   "permissions": [
      "cookies",
      "activeTab"
   ],
   "host_permissions": [
      "<all_urls>"
   ],
   "background": {
      "service_worker": "background.js"
   },
   "content_scripts": [
      {
         "matches": [
            "<all_urls>"
         ],
         "js": [
            "js/cookie.js"
         ]
      }
   ],
   "default_locale": "en"
}
```

提示 `service_worker` 有错误：

`Error in event handler: TypeError: Error processing argument at index 0,`

可能是 `background.js` 里面使用的 API 有变更，但外行实在看不懂，还请大佬更新更新，谢谢了

**Comment by ckx000** [comment]
已更新至Manifest V3,请移步 [Releases](https://github.com/ckx000/get-cookies/releases)下载新版测试

**Comment by FrancisNGG** [comment]
> 已更新至Manifest V3,请移步 [Releases](https://github.com/ckx000/get-cookies/releases)下载新版测试

确认可用，感谢大佬付出
