### ISSUE TITLE
已经替换了新的getcookies助手，但是签到模板还是提示未安装

### ISSUE THREAD

**Issue by hecarli555** [ckx000/get-cookies#9]
已经替换了新的getcookies助手，但是签到模板还是提示未安装

**Comment by ckx000** [comment]
签到框架是哪一版？在看看扩展程序里助手是否有报错
我这边刚用latest版的20230601和chrome107测试了下没有问题

**Comment by FrancisNGG** [comment]
离线安装已解压插件包，然后需要在插件选项里面设置好需要使用该插件的网址 (如qiandao.today) 既可以正常使用，再次感谢大佬付出
